Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  # Проброс порта (опционально)
  config.vm.network "forwarded_port", guest: 22, host: 2222

  # Настройки виртуальной машины
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  # Создание файла с флагом
  config.vm.provision "shell", inline: <<-SHELL
    echo "flag{your_secret_flag}" > /opt/flag.txt
    chmod 644 /opt/flag.txt
  SHELL
end
